#!/bin/zsh

LAST_COMMAND_SUCCESS='✓'
LAST_COMMAND_FAILURE='✗'

LAST_COMMAND_SUCCESS_COLOUR=40
LAST_COMMAND_FAILURE_COLOUR=196

exit_code_prompt() {
    if [[ $? == 0 ]]; then
        echo "%F{$LAST_COMMAND_SUCCESS_COLOUR}$LAST_COMMAND_SUCCESS%f"
    else
        echo "%F{$LAST_COMMAND_FAILURE_COLOUR}$LAST_COMMAND_FAILURE $?%f"
    fi
}
