#!/bin/sh

# This is quite probably the best function of all time
z() {
    local zdir
    zdir=$(cd ~ && find Repositories Documents -maxdepth 5 -path '*/\.*' -prune \
    -o -type d -print 2> /dev/null | \
    fzf +m --select-1 --query="$@") &&
    cd "$HOME/$zdir"
}

list_dirs() {
    for dir in *; do
        if [ -d "$dir" ]; then
            echo "$dir/"
        fi
    done
}

zd() {
    local dir
    dir=$(list_dirs | fzf +m --select-1 --query="$@") && cd "$dir"
}

mkcd() {
    mkdir -p "$@" && cd "$@"
}

vimf() {
    local file
    file=$(ag -l -g "$1" | fzf --query="$1" --select-1 --exit-0 -m)
    [ -n "$file" ] && vim -p "$file"
}

gmkcd() {
    mkdir -p "$1" && cd "$1" && git init
}

vimag() {
    vim $(ag -l --nocolor "$1")
}

vimagu() {
    vim $(ag -l -U --nocolor "$1")
}
