#!/usr/bin/sh

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if ! { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
    alias tclear='tmux set-window-option synchronize-panes on ;\
        tmux send-keys 'C-l' ;\
        tmux set-window-option synchronize-panes off'
fi

alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias lt='ls -alt'
alias ...='cd ../../..'
alias cpbranch='git rev-parse --abbrev-ref HEAD | xsel --clipboard'
alias define='surfraw google define'
alias rl='[ -n "$R_OUTPUT" ] && eval "$R_OUTPUT" || echo -e "\$R_OUTPUT not set, run r or rr"'
alias openchanges='vim $(git diff HEAD --name-only | grep -v lock)'
