#!/bin/bash

# This is quite probably the best function of all time
z() {
    local zdir
    zdir=$(cd ~ && find * -path '*/\.*' -prune \
    -o -type d -print 2> /dev/null | \
    fzf +m --select-1 --query="$@") &&
    cd "$HOME/$zdir"
}

zd() {
    local dir
    dir=$(find ${1:-*} -path '*/\.*' -prune \
        -o -type d -print 2> /dev/null | fzf +m) &&
        cd "$dir"
}

mkcd() {
    mkdir -p "$@" && cd "$@"
}

# View markdown file in man pages style
# Function because aliases don't accept arguments
manmd() {
    pandoc -s -f markdown -t man $1 | man -l -
}

vimf() {
    local file
    file=$(fzf --query="$1" --select-1 --exit-0 -m)
    [ -n "$file" ] && vim -p "$file"
}
