#!/usr/bin/env bash
git clone https://github.com/Lokaltog/vim-easymotion ~/.vim/bundle/vim-easymotion
git clone git://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive
git clone git@github.com:kien/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim
git clone git@github.com:scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

mkdir -p ~/.vim/syntax
cp -f ./php.vim ~/.vim/syntax
