#!/bin/bash

_branch_complete() {
    local cur

    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    COMPREPLY=( $( compgen -W "`git for-each-ref --format='%(refname:short)'`" -- $cur ) )

    return 0
}

complete -F _branch_complete -o filenames g
