#!/bin/bash

_branch_complete() {
    local cur

    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    COMPREPLY=( $( compgen -W '`git branch -a 2>&1`' ) )

    return 0
}

complete -F _branch_complete -o filenames g
