#!/bin/bash
if [ $# -eq 0 ]; then
    git status
    exit 0
fi

function prompt_pull() {
    branch=$(git rev-parse --abbrev-ref HEAD)
    echo $branch
}

function git_pull_recurse() {
    for path in $(pwd)/*; do
        [ -d "${path}" ] || continue
        (cd ${path} && prompt_pull)
    done
}

OP=$1
shift
case "$OP" in
    a) git add $@ ;;
    b) git blame $@ ;;
    c) git commit $@ ;;
    d) git diff $@ ;;
    l) git log $@ ;;
    s) git status ;;
    m)
        if [ $# -eq 0 ]; then
            git merge -
        else
            git merge $@
        fi
        ;;
    ch)
        if [ $# -eq 0 ]; then
            git checkout -
        else
            git checkout $@
        fi
        ;;
    ps)
        if [ $# -eq 0 ]; then
            git push origin $(git rev-parse --abbrev-ref HEAD)
        else
            git push $@
        fi
        ;;
    pl)
        if [ $# -eq 0 ]; then
            git fetch && git pull origin $(git rev-parse --abbrev-ref HEAD)
        elif [ $1 == "--recurse" ]; then
            git_pull_recurse
        else
            git pull $@
        fi
        ;;
    *)
        git $OP $@
        ;;
esac
