#!/usr/bin/env ruby

require "yaml"

TODO_FILE = File.join(ENV['HOME'], 'Desktop', 'todo.yml')

def first_depth_count(hash)
  total = 0
  hash.each do |value|
    total += value[1].count
  end
  total
end

def write_yaml(todos)
  File.open(TODO_FILE, "w") do |file|
    file.write todos.to_yaml
  end
end

def print_todos(todos)
  return if todos == nil
  todos.each do |name, body|
    puts name
    body.each do |todo|
      puts "\t- " + todo
    end
  end
end

if File.file?(TODO_FILE)
  todos = YAML.load_file(TODO_FILE)
  todos = {} if todos == nil
else
  todos = {}
  write_yaml todos
end


if ARGV.count == 0
  print_todos todos
  exit 0
end

todo_name = ARGV.shift

if "--count" == todo_name
  puts first_depth_count todos
else
  todos[todo_name] = [] if todos[todo_name].nil?
  todos[todo_name] = todos[todo_name].push(ARGV.join(" "))
  write_yaml todos
end
