#!/usr/bin/env ruby

# I'm aware this is probably terrible ruby

require "yaml"

TODO_FILE = File.join(ENV['HOME'], 'Desktop', 'todo.yml')

def write_yaml(todos)
  File.open(TODO_FILE, "w") do |file|
    file.write todos.to_yaml
  end
end

def print_todos(todos)
  return if todos == nil
  todos.each do |name, body|
    puts [name, "-", body].join(" ")
  end
end

if File.file?(TODO_FILE)
  todos = YAML.load_file(TODO_FILE)
  todos = {} if todos == nil
else
  todos = {}
  write_yaml todos
end

if ARGV.count == 0
  print_todos todos
  exit 0
end

todo_name = ARGV.shift

if "--count" == todo_name
  puts todos.count
else
  todos[todo_name] = ARGV.join(" ")
  write_yaml todos
end
