alias reload!='. ~/.zshrc && echo "Zshrc Reloaded"'
alias -g ...='../../..'
alias -g groot='"$(git rev-parse --show-toplevel)"'
alias -g changes='git status --porcelain | cut -c 4- | grep -v lock'
alias -g lastchanges='git diff-tree --no-commit-id --name-only -r HEAD'
alias openchanges='(cd groot && vim $(changes))'
alias openlast='(cd groot && vim $(lastchanges))'
alias repo='basename "$(echo groot)"'
